const {
  // imagekit
  REACT_APP_IMAGEKIT_URL,
  REACT_APP_IMAGEKIT_PUBLIC_KEY,
  REACT_APP_IMAGEKIT_AUTH_URL,
  REACT_APP_IMAGEKIT_DELETE_URL,
  // firebase
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID,
  // mongo
  REACT_APP_MONGO_DB_NETWORK,
  REACT_APP_MONGO_DB_API_KEY,
  REACT_APP_MONGO_DB_DATA_SOURCE,
  REACT_APP_MONGO_DB_DATABASE,
} = process.env;

const config = {
  // image kit io
  imageKitIo: {
    imagekitUrl: REACT_APP_IMAGEKIT_URL,
    imagekitPublicKey: REACT_APP_IMAGEKIT_PUBLIC_KEY,
    imagekitAuthUrl: REACT_APP_IMAGEKIT_AUTH_URL,
    imagekitDeleteUrl: REACT_APP_IMAGEKIT_DELETE_URL,
  },
  // firebase
  firebaseConfig: {
    apiKey: REACT_APP_FIREBASE_API_KEY,
    authDomain: REACT_APP_FIREBASE_AUTH_DOMAIN,
    projectId: REACT_APP_FIREBASE_PROJECT_ID,
    storageBucket: REACT_APP_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
    appId: REACT_APP_FIREBASE_APP_ID,
  },
  // mongo
  mongoConfig: {
    // mongo
    dbNetwork: REACT_APP_MONGO_DB_NETWORK,
    dbAPIKey: REACT_APP_MONGO_DB_API_KEY,
    dbSource: REACT_APP_MONGO_DB_DATA_SOURCE,
    dbName: REACT_APP_MONGO_DB_DATABASE,
  },
};

export default config;
